### PR TITLE
Javascript Sprint Challenge

### PR DESCRIPTION
**Pull request by faulkenfett11**

### CODE REVIEW

**Comment by faulkenfett11** [comment]
after watching the solutions for the stretch goals I realized my mistakes!  I had
let cube = new **_CuboidMake_**r({
  length: 2,
  width: 2,
  height: 2
});

instead of:
let cube = new **_Cube_**({
  length: 2,
  width: 2,
  height: 2
});

which was making my new surfaceArea function not work as well as "we have a cube!"

**Comment by faulkenfett11** [comment]
after watching the solutions for the stretch goals I realized my mistakes! I had
let cube = new **_CuboidMaker_**({
length: 2,
width: 2,
height: 2
});

instead of:
let cube = new Cube({
length: 2,
width: 2,
height: 2
});

which was making my new surfaceArea function not work as well as "we have a cube!"

**Comment by faulkenfett11** [comment]
after watching the solutions for the stretch goals I realized my mistakes! I had
let cube = new **_CuboidMaker_**({
length: 2,
width: 2,
height: 2
});

instead of:
let cube = new **_Cube_**({
length: 2,
width: 2,
height: 2,
**_isCube: true_**
});

which was making my new surfaceArea function not work as well as "we have a cube!"

**Comment by DonnieU** [comment]
Push yourself to do the stretch problems even if it's after the deadline!

Good, clean code. Great commits, commit messages, and comments. Keep up the great work!

Rating (0-3): 2

**Pull request closed without merging**
